--- !ruby/object:RDoc::RI::ClassDescription 
attributes: 
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  name: defaults
  rw: R
class_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Configuration
- !ruby/struct:RDoc::Markup::Flow::RULE 
  width: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Configuration
constants: 
- !ruby/object:RDoc::RI::Constant 
  comment: []

  name: DEFAULTS
  value: "{       :stencil    => 'rhtml',       #:format     => 'html',       :pagelayout => 'page',       :postlayout => 'post',       :maxchars   => 500,     }"
full_name: Brite::Config
includes: []

instance_methods: []

name: Config
superclass: Object
